      const textElement = document.querySelector("#name");
      const button = document.querySelector("#btn");

      // Initialize a click counter
      let clickCount = 0;

      // Define an array of colors to cycle through
      const colors = [
        `AliceBlue`,
        `AntiqueWhite`,
        `Aqua`,
        `Aquamarine`,
        `Azure`,
        `Beige`,
        `Bisque`,
        `Black`,
        `BlanchedAlmond`,
        `Blue`,
        `BlueViolet`,
        `Brown`,
        `BurlyWood`,
        `CadetBlue`,
        `Chartreuse`,
        `Chocolate`,
        `Coral`,
        `CornflowerBlue`,
        `Cornsilk`,
        `Crimson`,
        `Cyan`,
        `DarkBlue`,
        `DarkCyan`,
        `DarkGoldenRod`,
        `DarkGray`,
        `DarkGrey`,
        `DarkGreen`,
        `DarkKhaki`,
        `DarkMagenta`,
        `DarkOliveGreen`,
        `Darkorange`,
        `DarkOrchid`,
        `DarkRed`,
        `DarkSalmon`,
        `DarkSeaGreen`,
        `DarkSlateBlue`,
        `DarkSlateGray`,
        `DarkSlateGrey`,
        `DarkTurquoise`,
        `DarkViolet`,
        `DeepPink`,
        `DeepSkyBlue`,
        `DimGray`,
        `DimGrey`,
        `DodgerBlue`,
        `FireBrick`,
        `FloralWhite`,
        `ForestGreen`,
        `Fuchsia`,
        `Gainsboro`,
        `GhostWhite`,
        `Gold`,
        `GoldenRod`,
        `Gray`,
        `Grey`,
        `Green`,
        `GreenYellow`,
        `HoneyDew`,
        `HotPink`,
        `IndianRed`,
        `Indigo`,
        `Ivory`,
        `Khaki`,
        `Lavender`,
        `LavenderBlush`,
        `LawnGreen`,
        `LemonChiffon`,
        `LightBlue`,
        `LightCoral`,
        `LightCyan`,
        `LightGoldenRodYellow`,
        `LightGray`,
        `LightGrey`,
        `LightGreen`,
        `LightPink`,
        `LightSalmon`,
        `LightSeaGreen`,
        `LightSkyBlue`,
        `LightSlateGray`,
        `LightSlateGrey`,
        `LightSteelBlue`,
        `LightYellow`,
        `Lime`,
        `LimeGreen`,
        `Linen`,
        `Magenta`,
        `Maroon`,
        `MediumAquaMarine`,
        `MediumBlue`,
        `MediumOrchid`,
        `MediumPurple`,
        `MediumSeaGreen`,
        `MediumSlateBlue`,
        `MediumSpringGreen`,
        `MediumTurquoise`,
        `MediumVioletRed`,
        `MidnightBlue`,
        `MintCream`,
        `MistyRose`,
        `Moccasin`,
        `NavajoWhite`,
        `Navy`,
        `OldLace`,
        `Olive`,
        `OliveDrab`,
        `Orange`,
        `OrangeRed`,
        `Orchid`,
        `PaleGoldenRod`,
        `PaleGreen`,
        `PaleTurquoise`,
        `PaleVioletRed`,
        `PapayaWhip`,
        `PeachPuff`,
        `Peru`,
        `Pink`,
        `Plum`,
        `PowderBlue`,
        `Purple`,
        `Red`,
        `RosyBrown`,
        `RoyalBlue`,
        `SaddleBrown`,
        `Salmon`,
        `SandyBrown`,
        `SeaGreen`,
        `SeaShell`,
        `Sienna`,
        `Silver`,
        `SkyBlue`,
        `SlateBlue`,
        `SlateGray`,
        `SlateGrey`,
        `Snow`,
        `SpringGreen`,
        `SteelBlue`,
        `Tan`,
        `Teal`,
        `Thistle`,
        `Tomato`,
        `Turquoise`,
        `Violet`,
        `Wheat`,
        `White`,
        `WhiteSmoke`,
        `Yellow`,
        `YellowGreen`,
      ];

      // Function to handle button clicks
      function handleButtonClick() {
        // Increment the click counter
        clickCount++;

        // Determine the color based on the click count
        const colorIndex = (clickCount - 1) % colors.length; // Use modulo to cycle through colors
        const selectedColor = colors[colorIndex];

        // Change the text color
        document.body.style.backgroundColor = selectedColor;

        // Log the current color to the console (optional for debugging)
        console.log(`Click ${clickCount}: Color changed to ${selectedColor}`);
      }

      // Attach the event listener to the button
      button.addEventListener("click", handleButtonClick);
